CREATE TABLE toolkits(
	employee_id	INT	PRIMARY KEY,
	first_name VARCHAR(20) NOT NULL,
	last_name VARCHAR(20) NOT NULL,
	email VARCHAR(50),	
	department VARCHAR(20),	
	salary NUMERIC(10,2),	
	joining_date DATE,	
	age INT	
);

📊 SQL Practice Questions (Beginner → Advanced)
🔹 Basic Queries

Q1. Display all records from TOOLKITS

SELECT * FROM TOOLKITS;

Q2. Add a new column CITY

ALTER TABLE TOOLKITS ADD COLUMN CITY VARCHAR(50);

Q3. Drop the column CITY

ALTER TABLE TOOLKITS DROP COLUMN CITY;

Q4. Rename column EMPLOYEE_ID to ID

ALTER TABLE TOOLKITS RENAME COLUMN EMPLOYEE_ID TO ID;

Q5. Update FIRST_NAME where ID = 3

UPDATE TOOLKITS SET FIRST_NAME = 'rohit' WHERE ID = 3;

Q6. Delete record where ID = 1

DELETE FROM TOOLKITS WHERE ID = 1;

Q7. Display first 5 records

SELECT * FROM TOOLKITS LIMIT 5;
🔹 Filtering Data

Q8. Employees from HR with age > 30

SELECT * FROM TOOLKITS WHERE DEPARTMENT = 'HR' AND AGE > 30;

Q9. Employees with age > 40 and salary > 4000

SELECT * FROM TOOLKITS WHERE AGE > 40 AND SALARY > 4000;

Q10. Show AGE and SALARY

SELECT AGE, SALARY FROM TOOLKITS;

Q11. Age between 55 and 60

SELECT * FROM TOOLKITS WHERE AGE BETWEEN 55 AND 60;

Q12. Unique departments

SELECT DISTINCT DEPARTMENT FROM TOOLKITS;

Q13. Employees joined after 2021-04-05

SELECT * FROM TOOLKITS WHERE JOINING_DATE >= '2021-04-05';

Q14. Finance department OR age > 60

SELECT * FROM TOOLKITS WHERE DEPARTMENT = 'Finance' OR AGE > 60;

Q15. NOT salary > 40000 and age > 20

SELECT * FROM TOOLKITS WHERE NOT SALARY > 40000 AND AGE > 20;
🔹 Sorting & Updates

Q16. Top 10 highest salaries

SELECT SALARY FROM TOOLKITS ORDER BY SALARY DESC LIMIT 10;

Q17. Increase age by 10 for Finance

UPDATE TOOLKITS SET AGE = AGE + 10 WHERE DEPARTMENT = 'Finance';

Q18. Multiply salary by 5 where age > 30

UPDATE TOOLKITS SET SALARY = SALARY * 5 WHERE AGE > 30;
🔹 Pattern Matching

Q19. Names starting with 'T'

SELECT * FROM TOOLKITS WHERE FIRST_NAME LIKE 'T%';

Q20. Department ends with 'R'

SELECT * FROM TOOLKITS WHERE DEPARTMENT LIKE '%R';

Q21. Department contains 'r'

SELECT * FROM TOOLKITS WHERE DEPARTMENT LIKE '%r%';
🔹 String Functions

Q22. Full name

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULL_NAME FROM TOOLKITS;

Q23. Department length

SELECT DEPARTMENT, LENGTH(DEPARTMENT) FROM TOOLKITS;

Q24. Uppercase department

SELECT DEPARTMENT, UPPER(DEPARTMENT) FROM TOOLKITS;

Q25. Lowercase department

SELECT DEPARTMENT, LOWER(DEPARTMENT) FROM TOOLKITS;

Q26. Trim spaces

SELECT TRIM(DEPARTMENT) FROM TOOLKITS;

Q27. Substring

SELECT SUBSTRING(DEPARTMENT,1,3) FROM TOOLKITS;

Q28. Replace HR with SD

SELECT REPLACE(DEPARTMENT,'HR','SD') FROM TOOLKITS;
🔹 Aggregate Functions

Q29. Count rows

SELECT COUNT(*) FROM TOOLKITS;

Q30. Max age

SELECT MAX(AGE) FROM TOOLKITS;

Q31. Min salary

SELECT MIN(SALARY) FROM TOOLKITS;

Q32. Average salary

SELECT ROUND(AVG(SALARY),2) FROM TOOLKITS;

Q33. Total salary

SELECT SUM(SALARY) FROM TOOLKITS;
🔹 Group By

Q34. Department-wise salary > 400000

SELECT DEPARTMENT, SUM(SALARY)
FROM TOOLKITS
GROUP BY DEPARTMENT
HAVING SUM(SALARY) > 400000
ORDER BY SUM(SALARY) DESC;

Q35. Rollup total

SELECT COALESCE(DEPARTMENT,'Total'), SUM(SALARY)
FROM TOOLKITS
GROUP BY ROLLUP(DEPARTMENT);
🔹 Date Functions

Q36. Current time & date

SELECT NOW(), CURRENT_DATE, CURRENT_TIME;

Q37. Extract month

SELECT EXTRACT(MONTH FROM JOINING_DATE) FROM TOOLKITS;

Q38. Month name

SELECT TO_CHAR(JOINING_DATE,'month') FROM TOOLKITS;
🔹 Joins

Q39. Inner Join

SELECT * FROM EMP E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

Q40. Left Join

SELECT * FROM EMP E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

Q41. Right Join

SELECT * FROM EMP E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

Q42. Full Join

SELECT * FROM EMP E
FULL JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

Q43. Cross Join

SELECT * FROM EMP CROSS JOIN DEPARTMENTS;
🔹 Self Join

Q44. Employee and Manager

SELECT S.NAME, E.NAME AS MANAGER
FROM SEA S
LEFT JOIN SEA E ON S.MANAGER = E.ID;
🔹 Set Operations

Q45. UNION

SELECT * FROM EMPLOYEES_2024
UNION
SELECT * FROM EMPLOYEES_2023;

Q46. UNION ALL

SELECT * FROM EMPLOYEES_2023
UNION ALL
SELECT * FROM EMPLOYEES_2024;

Q47. EXCEPT

SELECT * FROM EMPLOYEES_2023
EXCEPT
SELECT * FROM EMPLOYEES_2024;

Q48. INTERSECT

SELECT * FROM EMPLOYEES_2023
INTERSECT
SELECT * FROM EMPLOYEES_2024;
🔹 Subqueries

Q49. Salary greater than all Finance

SELECT * FROM TOOLKITS
WHERE SALARY > ALL (
SELECT SALARY FROM TOOLKITS WHERE DEPARTMENT='Finance');

Q50. Second highest salary

SELECT * FROM TOOLKITS
WHERE SALARY = (
SELECT MAX(SALARY)
FROM TOOLKITS
WHERE SALARY < (SELECT MAX(SALARY) FROM TOOLKITS));




🔹 CASE Statements

Q51. Department category

SELECT DEPARTMENT,
CASE
WHEN DEPARTMENT='IT' THEN 'T'
WHEN DEPARTMENT='Marketing' THEN 'M'
ELSE 'Others'
END
FROM TOOLKITS;
🔹 Procedures & Functions

Q52. Procedure to update salary

CREATE OR REPLACE PROCEDURE CHANG_TABLE(EMP_ID INT, EMP_SALARY INT)
LANGUAGE PLPGSQL AS $$
BEGIN
UPDATE TOOLKITS SET SALARY = EMP_SALARY WHERE ID = EMP_ID;
END;
$$;

Q53. Insert procedure

CREATE OR REPLACE PROCEDURE CHECK_TABLE(...)

Q54.Window Function 

SELECT age,department,
SUM(age)  OVER( PARTITION BY department ) AS "Total",
AVG(age)  OVER( PARTITION BY department ) AS "Average",
COUNT(age)  OVER( PARTITION BY department ) AS "Count",
MIN(age)  OVER( PARTITION BY department ) AS "Min",
MAX(age)  OVER( PARTITION BY department) AS "Max"
FROM toolkits



SELECT age,
ROW_NUMBER()OVER(ORDER BY age) AS "ROW_NUMBER",
RANK() OVER(ORDER BY age) AS "RANK",
DENSE_RANK()OVER(ORDER BY age) AS "DENSE_RANK",
PERCENT_RANK() OVER(ORDER BY age) AS "PERCENT_RANK"
FROM toolkits



SELECT id,
FIRST_VALUE(id)  OVER( ORDER BY id) AS "FIRST_VALUE",
LAST_VALUE(id)  OVER( ORDER BY id) AS "LAST_VALUE",  
LEAD(id)  OVER( ORDER BY id) AS "LEAD",
LAG(id)  OVER( ORDER BY id) AS "LAG"
FROM toolkits

SELECT id,
LEAD(id, 2)  OVER( ORDER BY id) AS "LEAD_by2",
LAG(id, 2)  OVER( ORDER BY id) AS "LAG_by2"
FROM toolkits

Q55. Function create
CREATE FUNCTION CALCULATOR (
	IN A INT,
	IN B INT,
	OUT ADDITION INT,
	OUT SUBTRACTION INT,
	OUT MULTIPLICATION INT,
	OUT DIVIDE INT
) LANGUAGE PLPGSQL AS $$
begin
Addition = a+b;
Subtraction = a-b;
Multiplication = a*b;
Divide = a/b;
end;
$$
SELECT
	*
FROM
	CALCULATOR (12, 12)





